# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mieanalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = PlotWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(19, 19, 541, 521))
        self.graphWidget.setObjectName("graphWidget")
        self.setup_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.setup_groupBox.setGeometry(QtCore.QRect(570, 10, 221, 71))
        self.setup_groupBox.setObjectName("setup_groupBox")
        self.wavelength_label = QtWidgets.QLabel(self.setup_groupBox)
        self.wavelength_label.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.wavelength_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wavelength_label.setObjectName("wavelength_label")
        self.wavelength_lineEdit = QtWidgets.QLineEdit(self.setup_groupBox)
        self.wavelength_lineEdit.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.wavelength_lineEdit.setObjectName("wavelength_lineEdit")
        self.wavelengthUnits_label = QtWidgets.QLabel(self.setup_groupBox)
        self.wavelengthUnits_label.setGeometry(QtCore.QRect(190, 20, 21, 21))
        self.wavelengthUnits_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wavelengthUnits_label.setObjectName("wavelengthUnits_label")
        self.screenDistance_label_2 = QtWidgets.QLabel(self.setup_groupBox)
        self.screenDistance_label_2.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.screenDistance_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.screenDistance_label_2.setObjectName("screenDistance_label_2")
        self.screenDistance_lineEdit = QtWidgets.QLineEdit(self.setup_groupBox)
        self.screenDistance_lineEdit.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.screenDistance_lineEdit.setObjectName("screenDistance_lineEdit")
        self.scrrenDistanceUnits_label = QtWidgets.QLabel(self.setup_groupBox)
        self.scrrenDistanceUnits_label.setGeometry(QtCore.QRect(190, 40, 21, 21))
        self.scrrenDistanceUnits_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrrenDistanceUnits_label.setObjectName("scrrenDistanceUnits_label")
        self.mieScattering_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mieScattering_groupBox.setGeometry(QtCore.QRect(570, 90, 221, 71))
        self.mieScattering_groupBox.setObjectName("mieScattering_groupBox")
        self.refractiveIndex_label = QtWidgets.QLabel(self.mieScattering_groupBox)
        self.refractiveIndex_label.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.refractiveIndex_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.refractiveIndex_label.setObjectName("refractiveIndex_label")
        self.refractiveIndex_lineEdit = QtWidgets.QLineEdit(self.mieScattering_groupBox)
        self.refractiveIndex_lineEdit.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.refractiveIndex_lineEdit.setObjectName("refractiveIndex_lineEdit")
        self.extinctionCoefficient_label = QtWidgets.QLabel(self.mieScattering_groupBox)
        self.extinctionCoefficient_label.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.extinctionCoefficient_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extinctionCoefficient_label.setObjectName("extinctionCoefficient_label")
        self.extinctionCoefficient_lineEdit = QtWidgets.QLineEdit(self.mieScattering_groupBox)
        self.extinctionCoefficient_lineEdit.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.extinctionCoefficient_lineEdit.setObjectName("extinctionCoefficient_lineEdit")
        self.controls_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controls_groupBox.setGeometry(QtCore.QRect(570, 170, 221, 131))
        self.controls_groupBox.setObjectName("controls_groupBox")
        self.fibreDiameter_label = QtWidgets.QLabel(self.controls_groupBox)
        self.fibreDiameter_label.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.fibreDiameter_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fibreDiameter_label.setObjectName("fibreDiameter_label")
        self.fibreDiameter_lineEdit = QtWidgets.QLineEdit(self.controls_groupBox)
        self.fibreDiameter_lineEdit.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.fibreDiameter_lineEdit.setObjectName("fibreDiameter_lineEdit")
        self.fibreDiameterUnits_label = QtWidgets.QLabel(self.controls_groupBox)
        self.fibreDiameterUnits_label.setGeometry(QtCore.QRect(190, 20, 21, 21))
        self.fibreDiameterUnits_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fibreDiameterUnits_label.setObjectName("fibreDiameterUnits_label")
        self.fraunhoferDiameter_label = QtWidgets.QLabel(self.controls_groupBox)
        self.fraunhoferDiameter_label.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.fraunhoferDiameter_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fraunhoferDiameter_label.setObjectName("fraunhoferDiameter_label")
        self.fraunhoferDiameter_lineEdit = QtWidgets.QLineEdit(self.controls_groupBox)
        self.fraunhoferDiameter_lineEdit.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.fraunhoferDiameter_lineEdit.setObjectName("fraunhoferDiameter_lineEdit")
        self.fraunhoferDiameterUnits_label = QtWidgets.QLabel(self.controls_groupBox)
        self.fraunhoferDiameterUnits_label.setGeometry(QtCore.QRect(190, 40, 21, 21))
        self.fraunhoferDiameterUnits_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fraunhoferDiameterUnits_label.setObjectName("fraunhoferDiameterUnits_label")
        self.mieScattering_radioButton = QtWidgets.QRadioButton(self.controls_groupBox)
        self.mieScattering_radioButton.setGeometry(QtCore.QRect(20, 80, 91, 17))
        self.mieScattering_radioButton.setChecked(True)
        self.mieScattering_radioButton.setObjectName("mieScattering_radioButton")
        self.analysisMethod_buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.analysisMethod_buttonGroup.setObjectName("analysisMethod_buttonGroup")
        self.analysisMethod_buttonGroup.addButton(self.mieScattering_radioButton)
        self.fraunhoferApproximation_radioButton = QtWidgets.QRadioButton(self.controls_groupBox)
        self.fraunhoferApproximation_radioButton.setGeometry(QtCore.QRect(20, 100, 151, 17))
        self.fraunhoferApproximation_radioButton.setObjectName("fraunhoferApproximation_radioButton")
        self.analysisMethod_buttonGroup.addButton(self.fraunhoferApproximation_radioButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mie Analyzer"))
        self.setup_groupBox.setTitle(_translate("MainWindow", "Setup"))
        self.wavelength_label.setText(_translate("MainWindow", "Wavelength:"))
        self.wavelength_lineEdit.setText(_translate("MainWindow", "532"))
        self.wavelengthUnits_label.setText(_translate("MainWindow", "nm"))
        self.screenDistance_label_2.setText(_translate("MainWindow", "Screen Distance:"))
        self.screenDistance_lineEdit.setText(_translate("MainWindow", "40.58"))
        self.scrrenDistanceUnits_label.setText(_translate("MainWindow", "cm"))
        self.mieScattering_groupBox.setTitle(_translate("MainWindow", "Mie Scattering"))
        self.refractiveIndex_label.setText(_translate("MainWindow", "Refractive Index:"))
        self.refractiveIndex_lineEdit.setText(_translate("MainWindow", "2.27"))
        self.extinctionCoefficient_label.setText(_translate("MainWindow", "Extinction Coefficient:"))
        self.extinctionCoefficient_lineEdit.setText(_translate("MainWindow", "0.64"))
        self.controls_groupBox.setTitle(_translate("MainWindow", "Controls"))
        self.fibreDiameter_label.setText(_translate("MainWindow", "Fibre Diameter:"))
        self.fibreDiameter_lineEdit.setText(_translate("MainWindow", "20.00"))
        self.fibreDiameterUnits_label.setText(_translate("MainWindow", "μm"))
        self.fraunhoferDiameter_label.setText(_translate("MainWindow", "Fraunhofer Diameter:"))
        self.fraunhoferDiameter_lineEdit.setText(_translate("MainWindow", "16.74"))
        self.fraunhoferDiameterUnits_label.setText(_translate("MainWindow", "μm"))
        self.mieScattering_radioButton.setText(_translate("MainWindow", "Mie Scattering"))
        self.fraunhoferApproximation_radioButton.setText(_translate("MainWindow", "Fraunhofer Approximation"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

